{{- if eq .Values.mantis.config  "" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mantis.fullname" . }}-config
  labels:
    {{- include "mantis.labels" . | nindent 4 }}
data:
  config: {{ .Values.mantis.config }}

{{- end }}