apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mantis.fullname" . }}
  labels:
    {{- include "mantis.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mantis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mantis.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mantis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
          - |
              apt-get update
              apt-get install -y libldap2-dev libldb-dev
              cp /var/www/html/config/config_inc2.php /var/www/html/config/config_inc.php
              ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so
              ln -s /usr/lib/x86_64-linux-gnu/liblber.so /usr/lib/liblber.so
              docker-php-ext-install mysqli
              docker-php-ext-install pdo
              docker-php-ext-install pdo_mysql
              docker-php-ext-install ldap
              apache2-foreground
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - name: mantis
              mountPath: /var/www/html
            {{- if ne .Values.mantis.config  "" }}
            - name: config
              mountPath: /var/www/html/config/config_inc2.php
              subPath: config_inc.php
            {{- end }}
            - name: strings
              mountPath: /var/www/html/config/custom_strings_inc.php
              subPath: custom_strings_inc.php
            - name: constants
              mountPath: /var/www/html/config/custom_constants_inc.php
              subPath: custom_constants_inc.php
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: mantis
          persistentVolumeClaim:
            claimName: {{ include "mantis.fullname" . }}-app

        - name: config
          secret:
            {{- if eq .Values.mantis.predefinedConfigSecret  "" }}
            secretName: {{ include "mantis.fullname" . }}-config
            {{ else }}
            secretName: {{ .Values.mantis.predefinedConfigSecret }}
            {{- end }}
            items:
              - key: config_inc.php
                path: config_inc.php
        - name: strings
          configMap:
            name: {{ include "mantis.fullname" . }}-strings
            items:
              - key: custom_strings_inc.php
                path: custom_strings_inc.php
        - name: constants
          configMap:
            name: {{ include "mantis.fullname" . }}-constants
            items:
              - key: custom_constants_inc.php
                path: custom_constants_inc.php
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
