apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mantis.fullname" . }}
  labels:
    {{- include "mantis.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mantis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mantis.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mantis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-curl-app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.curlImage.repository }}:{{ .Values.curlImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: mantis
              mountPath: /mantis
          env:
            - name: VERSION
              value: {{ .Values.mantis.version }}
          command: ["sh", "-c"]
          args:
          - |
            curl -LO https://downloads.sourceforge.net/project/mantisbt/mantis-stable/${VERSION}/mantisbt-${VERSION}.zip
            unzip mantisbt-${VERSION}.zip
            mv mantisbt-${VERSION}/* /mantis
        - name: {{ .Chart.Name }}-git-addons
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gitImage.repository }}:{{ .Values.gitImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: mantis
              mountPath: /mantis
          env:
            - name: VERSION
              value: {{ .Values.mantis.version }}
          command: ["sh", "-c"]
          args:
            {{  range $key, $value := .Values.mantis.addons }}
              -  git clone -b {{ $value.tag }} {{ $value.url }}  /mantis/addons/{{ $value.name }}
            {{ end }}
              - exit 0
        - name: {{ .Chart.Name }}-busybox-chown
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.bbImage.repository }}:{{ .Values.bbImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: mantis
              mountPath: /mantis
          env:
            - name: VERSION
              value: {{ .Values.mantis.version }}
          command: ['sh', '-c', 'chown -R 33:33 /mantis && chmod 750 /mantis && echo done']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
          - |
              docker-php-ext-install mysqli
              docker-php-ext-install pdo
              docker-php-ext-install pdo_mysql
              apache2-foreground
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - name: mantis
              mountPath: /var/www/html
            {{- if ne .Values.mantis.config  "" }}
            - name: config
              mountPath: /var/www/html/config/config_inc.php
              subPath: config_inc.php
            {{- end }}
            - name: strings
              mountPath: /var/www/html/config/custom_strings_inc.php
              subPath: custom_strings_inc.php
            - name: constants
              mountPath: /var/www/html/config/custom_constants_inc.php
              subPath: custom_constants_inc.php
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: mantis
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "mantis.fullname" . }}-config
            items:
              - key: config_inc.php
                path: config_inc.php
        - name: strings
          configMap:
            name: {{ include "mantis.fullname" . }}-strings
            items:
              - key: custom_strings_inc.php
                path: custom_strings_inc.php
        - name: constants
          configMap:
            name: {{ include "mantis.fullname" . }}-constants
            items:
              - key: custom_constants_inc.php
                path: custom_constants_inc.php

      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
