apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mantis.fullname" . }}-strings
  labels:
    {{- include "mantis.labels" . | nindent 4 }}
data:
  custom_strings_inc.php: {{ .Values.mantis.custom_strings_inc | quote }}
