apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mantis.fullname" . }}-constants
  labels:
    {{- include "mantis.labels" . | nindent 4 }}
data:
  custom_constants_inc.php: {{ .Values.mantis.custom_constants_inc | quote }}
