{{- if eq .Values.mantis.predefinedConfigSecret  "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mantis.fullname" . }}-config
  labels:
    {{- include "mantis.labels" . | nindent 4 }}
data:
  config_inc.php: {{ .Values.mantis.config | b64enc | quote }}
{{- end }}
